Fix some `TypeError`s origination from `numpy` -> `torch` conversion
IBM/pymser pull request #7
Opened 2024-10-29 18:53 UTC by ab5424

# Summary

I observed some errors running the tutorial file, namely

```
File /rwthfs/rz/cluster/work/ab542498/venv/phonon_contribution_pymser/pymser/src/pymser/pymser.py:597, in equilibrate(input_data, LLM, batch_size, ADF_test, uncertainty, print_results)
    594 ac_time, uncorr_samples = calc_autocorrelation_time(equilibrated)
    596 # Calculates the average and standard deviation on the equilibrated data
--> 597 average, avg_uncertainty = calc_equilibrated_average(array_data,
    598                                                      t0,
    599                                                      uncertainty,
    600                                                      ac_time)
    602 # Create a dictionary with the results
    603 results_dict = {'MSE': MSEm_curve,
    604                 't0': t0,
    605                 'average': average,
   (...)
    608                 'ac_time': ac_time,
    609                 'uncorr_samples': uncorr_samples}

File /rwthfs/rz/cluster/work/ab542498/venv/phonon_contribution_pymser/pymser/src/pymser/pymser.py:301, in calc_equilibrated_average(data, eq_index, uncertainty, ac_time)
    298 # Calculate the uncorrelated Standard Error
    299 elif uncertainty == 'uSD':
    300     # Divide the equilibrated_data on uncorrelated chunks
--> 301     uncorr_batches = batch_average_data(equilibrated_data, np.ceil(ac_time).astype(int))
...
---> 87     truncated_data = data[:int(torch.floor(len(data) / batch_size) * batch_size)]
     89     # Reshape the data to create batch of size m.
     90     reshaped_data = torch.reshape(truncated_data, (-1, batch_size))

TypeError: floor(): argument 'input' (position 1) must be Tensor, not numpy.float64
```

and

```
File /rwthfs/rz/cluster/work/ab542498/venv/phonon_contribution_pymser/pymser/src/pymser/pymser.py:597, in equilibrate(input_data, LLM, batch_size, ADF_test, uncertainty, print_results)
    594 ac_time, uncorr_samples = calc_autocorrelation_time(equilibrated)
    596 # Calculates the average and standard deviation on the equilibrated data
--> 597 average, avg_uncertainty = calc_equilibrated_average(array_data,
    598                                                      t0,
    599                                                      uncertainty,
    600                                                      ac_time)
    602 # Create a dictionary with the results
    603 results_dict = {'MSE': MSEm_curve,
    604                 't0': t0,
    605                 'average': average,
   (...)
    608                 'ac_time': ac_time,
    609                 'uncorr_samples': uncorr_samples}

File /rwthfs/rz/cluster/work/ab542498/venv/phonon_contribution_pymser/pymser/src/pymser/pymser.py:301, in calc_equilibrated_average(data, eq_index, uncertainty, ac_time)
    298 # Calculate the uncorrelated Standard Error
    299 elif uncertainty == 'uSD':
    300     # Divide the equilibrated_data on uncorrelated chunks
--> 301     uncorr_batches = batch_average_data(equilibrated_data, np.ceil(ac_time).astype(int))
...
---> 90 reshaped_data = torch.reshape(truncated_data, (-1, batch_size))
     92 # Get the average of each batch
     93 averaged_batches = torch.tensor([torch.average(i) for i in reshaped_data])

TypeError: reshape(): argument 'input' (position 1) must be Tensor, not numpy.ndarray
```

which I think are related to commit [d6b9517](https://github.com/IBM/pymser/pull/6/commits/d6b9517551ca8e0b566489143b59b2b1fc1839eb). I changed some of the conversion between `numpy` and `torch` and at least the `pymser_tutorial.ipynb` now runs fine for me.

## Checklist

- [ ] I ran the appropriate tests.
- [ ] I ran `flake8 --max-line-length=100`.
- [ ] I wrote documentation for all new features.
- [ ] I have added any new dependencies (libraries and/or tools) to `setup.py`, `Pipfile` and `README.md`.

## Related Issue(s)

Closes #

## Notes to Reviewer

...

2024-10-29 20:22 UTC, ab5424 commented on src/pymser/pymser.py
> +        truncated_data = data[: int(len(data) / batch_size // 1 * batch_size)]
This is only a float and not an array/tensor so basic arithmetic (`// 1`) should be sufficient instead of `floor`

2024-10-29 20:22 UTC, ab5424 commented on src/pymser/pymser.py
> -        averaged_batches = torch.tensor([torch.average(i) for i in reshaped_data])
`torch.average` does not exist.

2024-12-06 20:04 UTC, neumannrf requested changes
Hi Alexander! Thank you very much for looking at the code with eagle eyes and making so many improvements.

Overall, all your edits are being accepted. I only made a suggestion for a further simplification in one line you provided. Please consider it below.

2024-12-06 20:04 UTC, neumannrf commented on src/pymser/pymser.py
> +        truncated_data = data[: int(len(data) / batch_size // 1 * batch_size)]
```suggestion
        truncated_data = data[:int(len(data) / batch_size) * batch_size]
```

2024-12-06 20:04 UTC, neumannrf commented on src/pymser/pymser.py
> -        averaged_batches = torch.tensor([torch.average(i) for i in reshaped_data])
Nice catch! 🤭 I don't know how this slipped past us.

2024-12-06 20:04 UTC, neumannrf commented on src/pymser/pymser.py
> +        truncated_data = data[: int(len(data) / batch_size // 1 * batch_size)]
There is possibly an even simpler version of that, considering that `batch_size` is an integer, so the product with `int()` will automatically be an integer as well.

2024-12-06 20:04 UTC, neumannrf commented on src/pymser/pymser.py
> +        [tau], _ = curve_fit(exp_decay, x, ACF)
Nice catch! 😉

2024-12-09 09:19 UTC, ab5424 commented
This is ready now I think.

2024-12-09 12:56 UTC, neumannrf approved these changes
Thank you very much for your contribution! 👏

2024-12-09 12:57 UTC, merged

2024-12-09 15:11 UTC, neumannrf commented
@ab5424 After a few (unrelated) tweaks I had to do in the code to satisfy the Flake8 linter, `pymser` version 1.0.21 was [published on Pypi.org](https://pypi.org/project/pymser/) including your contribution! 👏